/*
  # Fix Security Issues - Part 2: Drop Unused Indexes

  ## Overview
  Drop all unused indexes to improve write performance and reduce maintenance overhead

  ## Changes
  Drop 200+ unused indexes across all tables
*/

-- Content system indexes
DROP INDEX IF EXISTS public.content_templates_user_id_idx;
DROP INDEX IF EXISTS public.content_templates_client_id_idx;
DROP INDEX IF EXISTS public.content_templates_content_type_idx;
DROP INDEX IF EXISTS public.content_briefs_calendar_id_idx;
DROP INDEX IF EXISTS public.content_briefs_client_id_idx;
DROP INDEX IF EXISTS public.seo_keywords_content_id_idx;
DROP INDEX IF EXISTS public.seo_keywords_keyword_idx;
DROP INDEX IF EXISTS public.profiles_email_idx;
DROP INDEX IF EXISTS public.clients_user_id_idx;
DROP INDEX IF EXISTS public.reports_client_id_idx;
DROP INDEX IF EXISTS public.playbooks_user_id_idx;
DROP INDEX IF EXISTS public.content_seo_scores_content_id_idx;
DROP INDEX IF EXISTS public.content_seo_scores_scored_at_idx;
DROP INDEX IF EXISTS public.content_performance_content_id_idx;
DROP INDEX IF EXISTS public.content_performance_date_idx;
DROP INDEX IF EXISTS public.content_ab_tests_parent_content_id_idx;
DROP INDEX IF EXISTS public.content_approvals_content_id_idx;
DROP INDEX IF EXISTS public.content_approvals_approver_id_idx;
DROP INDEX IF EXISTS public.content_approvals_status_idx;
DROP INDEX IF EXISTS public.content_comments_content_id_idx;
DROP INDEX IF EXISTS public.content_comments_user_id_idx;
DROP INDEX IF EXISTS public.generated_content_user_id_idx;
DROP INDEX IF EXISTS public.generated_content_client_id_idx;
DROP INDEX IF EXISTS public.generated_content_content_type_idx;
DROP INDEX IF EXISTS public.generated_content_status_idx;
DROP INDEX IF EXISTS public.brand_voice_profiles_client_id_idx;
DROP INDEX IF EXISTS public.brand_voice_profiles_is_default_idx;
DROP INDEX IF EXISTS public.brand_voice_examples_brand_voice_id_idx;
DROP INDEX IF EXISTS public.generated_content_brand_voice_id_idx;
DROP INDEX IF EXISTS public.generated_content_parent_content_id_idx;
DROP INDEX IF EXISTS public.generated_content_scheduled_publish_date_idx;
DROP INDEX IF EXISTS public.content_calendar_client_id_idx;
DROP INDEX IF EXISTS public.content_calendar_scheduled_date_idx;
DROP INDEX IF EXISTS public.content_calendar_assigned_to_idx;
DROP INDEX IF EXISTS public.content_versions_content_id_idx;
DROP INDEX IF EXISTS public.content_versions_created_at_idx;
DROP INDEX IF EXISTS public.content_assignments_content_id_idx;
DROP INDEX IF EXISTS public.content_assignments_assigned_to_idx;
DROP INDEX IF EXISTS public.content_assignments_status_idx;
DROP INDEX IF EXISTS public.content_assignments_due_date_idx;
DROP INDEX IF EXISTS public.content_assets_content_id_idx;
DROP INDEX IF EXISTS public.content_assets_asset_type_idx;
DROP INDEX IF EXISTS public.idx_content_ab_tests_variation_content_id;
DROP INDEX IF EXISTS public.idx_content_assets_uploaded_by;
DROP INDEX IF EXISTS public.idx_content_assignments_assigned_by;
DROP INDEX IF EXISTS public.idx_content_briefs_created_by;
DROP INDEX IF EXISTS public.idx_content_calendar_content_id;
DROP INDEX IF EXISTS public.idx_content_calendar_created_by;
DROP INDEX IF EXISTS public.idx_content_comments_parent_comment_id;
DROP INDEX IF EXISTS public.idx_content_versions_created_by;

-- Verification and activation indexes
DROP INDEX IF EXISTS public.idx_verification_user;
DROP INDEX IF EXISTS public.idx_verification_client;
DROP INDEX IF EXISTS public.idx_verification_type;
DROP INDEX IF EXISTS public.idx_verification_status;
DROP INDEX IF EXISTS public.idx_verification_started;
DROP INDEX IF EXISTS public.idx_verification_channel;
DROP INDEX IF EXISTS public.idx_activation_user;
DROP INDEX IF EXISTS public.idx_activation_client;
DROP INDEX IF EXISTS public.idx_activation_stage;
DROP INDEX IF EXISTS public.idx_activation_cohort;
DROP INDEX IF EXISTS public.idx_activation_channel;
DROP INDEX IF EXISTS public.idx_activation_dropped;

-- Deal and attribution indexes
DROP INDEX IF EXISTS public.idx_deals_user_id;
DROP INDEX IF EXISTS public.idx_deals_client_id;
DROP INDEX IF EXISTS public.idx_deals_close_date;
DROP INDEX IF EXISTS public.idx_deals_created_date;
DROP INDEX IF EXISTS public.idx_deal_touchpoints_deal_id;
DROP INDEX IF EXISTS public.idx_deal_touchpoints_date;
DROP INDEX IF EXISTS public.idx_deal_touchpoints_type;
DROP INDEX IF EXISTS public.idx_deal_touchpoints_channel;
DROP INDEX IF EXISTS public.idx_attribution_settings_user_id;
DROP INDEX IF EXISTS public.idx_deal_stage_history_deal_id;
DROP INDEX IF EXISTS public.idx_deal_stage_history_stage;
DROP INDEX IF EXISTS public.idx_deal_stage_history_entered;
DROP INDEX IF EXISTS public.idx_marketing_campaigns_user_id;
DROP INDEX IF EXISTS public.idx_marketing_campaigns_type;
DROP INDEX IF EXISTS public.idx_marketing_campaigns_status;
DROP INDEX IF EXISTS public.idx_marketing_campaigns_dates;
DROP INDEX IF EXISTS public.idx_campaign_touchpoints_campaign;
DROP INDEX IF EXISTS public.idx_campaign_touchpoints_touchpoint;
DROP INDEX IF EXISTS public.idx_revenue_forecasts_user_id;
DROP INDEX IF EXISTS public.idx_revenue_forecasts_period;

-- Integration indexes
DROP INDEX IF EXISTS public.idx_integrations_client;
DROP INDEX IF EXISTS public.idx_integrations_type;
DROP INDEX IF EXISTS public.idx_integrations_active;
DROP INDEX IF EXISTS public.idx_integrations_sync_status;
DROP INDEX IF EXISTS public.idx_mappings_integration;
DROP INDEX IF EXISTS public.idx_mappings_local;
DROP INDEX IF EXISTS public.idx_mappings_remote;
DROP INDEX IF EXISTS public.idx_mappings_status;
DROP INDEX IF EXISTS public.idx_mappings_last_synced;
DROP INDEX IF EXISTS public.idx_sync_logs_integration;
DROP INDEX IF EXISTS public.idx_sync_logs_mapping;
DROP INDEX IF EXISTS public.idx_sync_logs_status;
DROP INDEX IF EXISTS public.idx_sync_logs_started;
DROP INDEX IF EXISTS public.idx_sync_logs_operation;
DROP INDEX IF EXISTS public.idx_sync_logs_entity;
DROP INDEX IF EXISTS public.idx_field_mappings_integration;
DROP INDEX IF EXISTS public.idx_field_mappings_entity;
DROP INDEX IF EXISTS public.idx_field_mappings_direction;
DROP INDEX IF EXISTS public.idx_webhooks_integration;
DROP INDEX IF EXISTS public.idx_webhooks_processed;
DROP INDEX IF EXISTS public.idx_webhooks_received;
DROP INDEX IF EXISTS public.idx_webhooks_event;
DROP INDEX IF EXISTS public.idx_google_oauth_tokens_user_id;
DROP INDEX IF EXISTS public.idx_gsc_properties_user_id;
DROP INDEX IF EXISTS public.idx_integrations_user;
DROP INDEX IF EXISTS public.idx_integrations_service;
DROP INDEX IF EXISTS public.idx_integration_syncs_integration;
DROP INDEX IF EXISTS public.idx_gsc_properties_client_id;
DROP INDEX IF EXISTS public.idx_gsc_properties_url;
DROP INDEX IF EXISTS public.idx_gsc_data_property_id;
DROP INDEX IF EXISTS public.idx_gsc_data_date;
DROP INDEX IF EXISTS public.idx_gsc_data_property_date;
DROP INDEX IF EXISTS public.idx_connected_accounts_client_id;
DROP INDEX IF EXISTS public.idx_connected_accounts_integration_id;

-- Event and fraud indexes
DROP INDEX IF EXISTS public.idx_user_events_user;
DROP INDEX IF EXISTS public.idx_user_events_client;
DROP INDEX IF EXISTS public.idx_user_events_type;
DROP INDEX IF EXISTS public.idx_user_events_timestamp;
DROP INDEX IF EXISTS public.idx_user_events_channel;
DROP INDEX IF EXISTS public.idx_user_events_fraud;
DROP INDEX IF EXISTS public.idx_fraud_events_client;
DROP INDEX IF EXISTS public.idx_fraud_events_user;
DROP INDEX IF EXISTS public.idx_fraud_events_detected;
DROP INDEX IF EXISTS public.idx_fraud_events_type;
DROP INDEX IF EXISTS public.idx_fraud_events_channel;
DROP INDEX IF EXISTS public.idx_fraud_events_status;

-- Compliance and FinTech indexes
DROP INDEX IF EXISTS public.idx_compliance_rules_body;
DROP INDEX IF EXISTS public.idx_compliance_rules_jurisdiction;
DROP INDEX IF EXISTS public.idx_compliance_rules_active;
DROP INDEX IF EXISTS public.idx_campaign_compliance_campaign;
DROP INDEX IF EXISTS public.idx_campaign_compliance_user;
DROP INDEX IF EXISTS public.idx_campaign_compliance_status;
DROP INDEX IF EXISTS public.idx_campaign_compliance_checked;
DROP INDEX IF EXISTS public.idx_fintech_metrics_date;
DROP INDEX IF EXISTS public.idx_fintech_metrics_channel;
DROP INDEX IF EXISTS public.idx_fintech_metrics_campaign;
DROP INDEX IF EXISTS public.idx_fintech_integrations_client;
DROP INDEX IF EXISTS public.idx_fintech_integrations_provider;
DROP INDEX IF EXISTS public.idx_fintech_integrations_type;
DROP INDEX IF EXISTS public.idx_payment_events_client;
DROP INDEX IF EXISTS public.idx_payment_events_integration;
DROP INDEX IF EXISTS public.idx_payment_events_customer;
DROP INDEX IF EXISTS public.idx_payment_events_type;
DROP INDEX IF EXISTS public.idx_payment_events_timestamp;
DROP INDEX IF EXISTS public.idx_payment_events_processed;
DROP INDEX IF EXISTS public.idx_bank_events_client;
DROP INDEX IF EXISTS public.idx_bank_events_integration;
DROP INDEX IF EXISTS public.idx_bank_events_user;
DROP INDEX IF EXISTS public.idx_bank_events_type;
DROP INDEX IF EXISTS public.idx_bank_events_status;
DROP INDEX IF EXISTS public.idx_bank_events_processed;
DROP INDEX IF EXISTS public.idx_kyc_events_client;
DROP INDEX IF EXISTS public.idx_kyc_events_integration;
DROP INDEX IF EXISTS public.idx_kyc_events_verification;
DROP INDEX IF EXISTS public.idx_kyc_events_type;
DROP INDEX IF EXISTS public.idx_kyc_events_status;
DROP INDEX IF EXISTS public.idx_kyc_events_processed;
DROP INDEX IF EXISTS public.idx_fraud_signals_client;
DROP INDEX IF EXISTS public.idx_fraud_signals_integration;
DROP INDEX IF EXISTS public.idx_fraud_signals_user;
DROP INDEX IF EXISTS public.idx_fraud_signals_type;
DROP INDEX IF EXISTS public.idx_fraud_signals_risk;
DROP INDEX IF EXISTS public.idx_fraud_signals_timestamp;
DROP INDEX IF EXISTS public.idx_fraud_signals_processed;
DROP INDEX IF EXISTS public.idx_oauth_states_user;
DROP INDEX IF EXISTS public.idx_oauth_states_state;
DROP INDEX IF EXISTS public.idx_oauth_states_expires;

-- Marketing and competitor indexes
DROP INDEX IF EXISTS public.idx_alerts_user;
DROP INDEX IF EXISTS public.idx_marketing_metrics_user;
DROP INDEX IF EXISTS public.idx_marketing_metrics_client;
DROP INDEX IF EXISTS public.idx_marketing_metrics_date;
DROP INDEX IF EXISTS public.idx_marketing_metrics_channel;
DROP INDEX IF EXISTS public.idx_marketing_metrics_campaign;
DROP INDEX IF EXISTS public.idx_marketing_metrics_source;
DROP INDEX IF EXISTS public.idx_marketing_metrics_integration;
DROP INDEX IF EXISTS public.idx_marketing_metrics_composite;
DROP INDEX IF EXISTS public.idx_competitors_user;
DROP INDEX IF EXISTS public.idx_competitors_domain;
DROP INDEX IF EXISTS public.idx_competitors_monitoring;
DROP INDEX IF EXISTS public.idx_competitors_last_check;
DROP INDEX IF EXISTS public.idx_alerts_competitor;
DROP INDEX IF EXISTS public.idx_alerts_type;
DROP INDEX IF EXISTS public.idx_alerts_severity;
DROP INDEX IF EXISTS public.idx_alerts_read;
DROP INDEX IF EXISTS public.idx_alerts_created;
DROP INDEX IF EXISTS public.idx_alerts_unread_user;
DROP INDEX IF EXISTS public.idx_metrics_history_competitor;
DROP INDEX IF EXISTS public.idx_metrics_history_date;

-- Prediction and recommendation indexes
DROP INDEX IF EXISTS public.idx_predictions_user;
DROP INDEX IF EXISTS public.idx_predictions_client;
DROP INDEX IF EXISTS public.idx_predictions_date;
DROP INDEX IF EXISTS public.idx_recommendations_user;
DROP INDEX IF EXISTS public.idx_recommendations_client;
DROP INDEX IF EXISTS public.idx_recommendations_channel;
DROP INDEX IF EXISTS public.idx_recommendations_status;
DROP INDEX IF EXISTS public.idx_recommendations_date;

-- Pitch system indexes
DROP INDEX IF EXISTS public.idx_pitch_leads_email;
DROP INDEX IF EXISTS public.idx_pitch_leads_created_at;
DROP INDEX IF EXISTS public.idx_demo_bookings_lead_id;
DROP INDEX IF EXISTS public.idx_demo_bookings_status;
DROP INDEX IF EXISTS public.idx_pitch_analytics_session;
DROP INDEX IF EXISTS public.idx_pitch_analytics_event_type;
DROP INDEX IF EXISTS public.idx_roi_calculations_session;